FROM --platform=$BUILDPLATFORM golang:1.19-buster as builder

ARG TARGETOS
ARG TARGETARCH

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go install github.com/touilleio/tee-hash@latest

FROM --platform=$BUILDPLATFORM ubuntu:22.04

COPY --from=builder /go/bin/tee-hash /usr/local/bin/tee-hash

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y awscli postgresql-client-14 && \
    apt clean && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
